#!/bin/sh


echo Content-type: text/html
echo

rm -f ../values 

touch values
i=1;
while [ $i -le 47 ]
do

echo "$QUERY_STRING" | cut -d"&" -f$i | cut -d"=" =f2 | > values

i='expr $i + 1'

done

cp values ../

echo "Processing...."
echo "<meta http-equiv=\"refresh\" content=\"1;url=../values\">"
